{{ if .Values.grafana.enabled }} 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.grafana.syncWave | default "0" | quote }}
spec:
  project: {{ .Values.global.project }}
  destination: 
    namespace: {{ .Values.grafana.namespace }}
    server: {{ .Values.global.clusterURL }}
  source:
    repoURL: {{ .Values.grafana.source.repoURL }}
    chart: {{ .Values.grafana.source.chart }} 
    targetRevision: {{ .Values.grafana.source.targetRevision | default "HEAD" }}
    helm:
      releaseName: {{ .Values.grafana.name }}
{{- with .Values.grafana.values }}
      values: |-
{{- toYaml . | nindent 8 }}
{{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: route.openshift.io/v1                                                                                    
kind: Route                                                                                                          
metadata:                                                                                                                                                                                                                                                                        
  name: {{ .Values.grafana.name }}                                                                                               
  namespace: {{ .Values.grafana.namespace }}                                                                                                                                                                       
spec:                                                                                                                
  host: {{ .Values.grafana.name }}.{{ .Values.global.baseDomain }}                                  
  port:                                                                                                              
    targetPort: service                                                                                       
  to:                                                                                                                
    kind: Service                                                                                                    
    name: {{ .Values.grafana.name }}                                                                                             
    weight: 100                                                                                                      
  wildcardPolicy: None       
{{ end }}